# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "test"

  config.vm.box = ENV['BOX_NAME'] || "coreos"

  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.provider :virtualbox do |vb, override|
    override.vm.network :private_network, ip: "192.168.33.10"
#    override.vm.network :private_network, type: "dhcp"
#    override.vm.network :public_network, bridge: "en0: Wi-Fi (AirPort)"
#    override.vm.network :public_network, bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.1.201"
  end
  config.vm.provider :parallels do |prl, override|
    override.vm.network :private_network, ip: "192.168.34.10"
#    override.vm.network :private_network, type: "dhcp"
#    override.vm.network :public_network, bridge: "en0"
#    override.vm.network :public_network, bridge: "en0", ip: "192.168.1.201"
  end

  config.vm.synced_folder ".", "/home/core/vagrant", id: "core", type: "nfs",  mount_options: ["nolock", "vers=3", "udp"]

  config.vm.provision :docker do |d|
    d.pull_images "yungsang/busybox"
    d.run "simple-echo",
      image: "yungsang/busybox",
      args: "-p 8080:8080",
      cmd: "nc -p 8080 -l -l -e echo hello world!"
  end

  config.vm.network :forwarded_port, guest: 8080, host: 8080
end
