# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "coreos"

  config.vm.network "forwarded_port", guest: 4243, host: 4243

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder ".", "/home/core/vagrant", id: "core", type: "nfs",  mount_options: ['nolock,vers=3,udp']

  config.vm.provision :docker do |d|
    d.pull_images "busybox"
    d.run "busybox",
      cmd: "echo hello"
  end
end
